# Generated by Django 5.0.6 on 2024-07-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(max_length=20)),
                ('Fullname_ursername', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Issue_quriy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(max_length=20)),
                ('Fullname_ursername', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Issue_quriy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_Quiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(max_length=20)),
                ('Fullname_ursername', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Issue_quriy', models.TextField()),
            ],
        ),
    ]
