# Generated by Django 5.0.6 on 2024-06-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Date_Of_Brith', models.DateField()),
                ('Roll_No', models.IntegerField()),
                ('Phone_No', models.BigIntegerField()),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
