# Generated by Django 5.0.6 on 2024-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Register_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Middle_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Date_Of_Brith', models.DateField()),
                ('Roll_No', models.IntegerField()),
                ('Phone_No', models.BigIntegerField()),
                ('PEmail_ID', models.EmailField(max_length=254)),
                ('CEmail_ID', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Confrimed_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Login_Page',
        ),
    ]
